content_mcupekerja/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('home', ['uses' => 'FrontController@Index', 'as' => 'home']);
Route::get('thanks', ['uses' => 'RegController@thanks', 'as' => 'thanks']);
Route::get('mitra-kami', ['uses' => 'FrontController@MitraKami', 'as' => 'mitra-kami']);
Route::get('tentang-kami', ['uses' => 'FrontController@TentangKami', 'as' => 'tentang-kami']);
Route::get('register', ['uses' => 'RegController@index', 'as' => 'register']);
// Route::get('cek-voucher/{kode}', ['uses' => 'FrontController@CekVoucher', 'as' => 'cek-voucher']);
Route::get('pdf', ['uses' => 'RegController@makepdf', 'as' => 'pdf']);
Route::get('gpdf', ['uses' => 'RegController@genpdf', 'as' => 'gpdf']);
Route::post('save-register', ['uses' => 'RegController@store', 'as' => 'save-register']);

Route::get('home-admin', array('middleware' => 'auth', 'uses' => 'FrontController@AdminHome', 'as' => 'home-admin'));
// Route::get('kelola-kode', array('middleware' => 'auth', 'uses' => 'FrontController@KelolaKode', 'as' => 'kelola-kode'));
Route::get('kelola-user', array('middleware' => 'auth', 'uses' => 'FrontController@KelolaUser', 'as' => 'kelola-user'));
Route::get('form-user', array('middleware' => 'auth', 'uses' => 'FrontController@FormUser', 'as' => 'form-user'));
Route::post('save-user', array('middleware' => 'auth', 'uses' => 'FrontController@SaveUser', 'as' => 'save-user'));
// Route::post('save-kode', array('middleware' => 'auth', 'uses' => 'FrontController@SaveKode', 'as' => 'save-kode'));
Route::get('laporan-registrasi', array('middleware' => 'auth', 'uses' => 'FrontController@LaporanRegistrasi', 'as' => 'laporan-registrasi'));
Route::get('data-listuser', array('middleware' => 'auth', 'uses' => 'FrontController@ListUser', 'as' => 'data-listuser'));
Route::get('data-listkode', array('middleware' => 'auth', 'uses' => 'FrontController@ListKode', 'as' => 'data-listkode'));
Route::post('delete-user', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteUser', 'as' => 'delete-user'));
// Route::post('delete-kode', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteKode', 'as' => 'delete-kode'));

Route::post('delete-registrasi', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteRegistrasi', 'as' => 'delete-registrasi'));
Route::get('data-listregistrasi', array('middleware' => 'auth', 'uses' => 'FrontController@ListRegistrasi', 'as' => 'data-listregistrasi'));
Route::get('detil-registrasi/{id}', array('middleware' => 'auth', 'uses' => 'FrontController@DetilRegistrasi', 'as' => 'detil-registrasi'));
Route::get('export-excel/{word?}', array('middleware' => 'auth', 'uses' => 'FrontController@ExportExcel', 'as' => 'export-excel'));

Route::get('auth/login', array('uses' => 'Auth\AuthController@getLogin', 'as' => 'login'));
Route::post('auth/login', array('uses' => 'Auth\AuthController@postLogin', 'as' => 'postLogin'));
// Route::get('auth/register', array('uses' => 'Auth\AuthController@getRegister', 'as' => 'register'));
// Route::post('auth/register', array('uses' => 'Auth\AuthController@postRegister', 'as' => 'postRegister'));
Route::get('auth/logout', array('uses' => 'Auth\AuthController@getLogout', 'as' => 'logout'));

Route::get('/', function () {
    return redirect()->route('home');
});

Route::group(['middleware' => 'auth', 'prefix' => 'mst'], function () {

	Route::resource('kota', 'KotaController',
      ['except' => ['show']]);
	Route::resource('parameter', 'ParameterController',
      ['except' => ['show']]);
	Route::resource('margin', 'MarginController',
      ['except' => ['show']]);
	Route::resource('paket', 'PaketController',
      ['except' => ['show']]);
	Route::resource('notif', 'NotifController',
      ['except' => ['show']]);
	Route::get('parameter/price/{id}', 
		['uses' => 'ParameterController@price', 
		'as' => 'mst.parameter.price']);
	Route::post('parameter/price/', 
		['uses' => 'ParameterController@saveprice', 
		'as' => 'mst.parameter.save']);
	Route::get('paket/price/{id}', 
		['uses' => 'PaketController@price', 
		'as' => 'mst.paket.price']);
	Route::post('paket/price/', 
		['uses' => 'PaketController@saveprice', 
		'as' => 'mst.paket.save']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'src'], function () {
	Route::get('kota', ['uses' => 'SrcController@Kota', 'as' => 'src.kota']);
	Route::get('parameter', ['uses' => 'SrcController@Parameter', 'as' => 'src.parameter']);
	Route::get('paket', ['uses' => 'SrcController@Paket', 'as' => 'src.paket']);
	Route::get('margin', ['uses' => 'SrcController@Margin', 'as' => 'src.margin']);
	Route::get('notif', ['uses' => 'SrcController@Notif', 'as' => 'src.notif']);
	Route::get('paket-param/{id}', ['uses' => 'SrcController@PaketParam', 'as' => 'src.paket-param']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'tx'], function () {
	Route::get('param/{id}', ['uses' => 'TxController@param', 'as' => 'tx.param']);
	Route::get('create/{id}', ['uses' => 'TxController@create', 'as' => 'tx.create']);
	Route::post('save/{id}', ['uses' => 'TxController@save', 'as' => 'tx.save']);
	Route::delete('param/{id}', ['uses' => 'TxController@del', 'as' => 'tx.del']);
	
});

content_mcupekerja/app/Margin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Margin extends Model
{
    protected $table = 'margin';
    protected $fillable = ['margin'];
}

content_mcupekerja/app/Http/Controllers/MarginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Margin;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use Validator;

class MarginController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('margin.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('margin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'margin' => 'required|integer|between:1,100'
        ];

        $messages = [
            'required'  => 'Margin harus diisi!',
            'integer'  => 'margin harus berupa angka',
            'between'  => 'margin harus berupa angka antara 1 sampai dengan 100',
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return redirect()->route('tx.create-margin')->withInput()->withErrors($validator);
        } else {
            $margin = new Margin();
            $margin->dari = trim($request['dari']);
            $margin->ke = trim($request['ke']);
            $margin->margin = trim($request['margin']);
            $margin->save();
            $request->session()->flash('statusmargin', 'Tersimpan!');
        }

        return redirect()->route('mst.margin.index')->with('statusmargin', 'Tersimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $margin = Margin::findOrFail($id);
        return view('margin.edit', ['margin'=>$margin]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'margin' => 'required|integer|between:1,100'
        ];

        $messages = [
            'required'  => 'Margin harus diisi!',
            'integer'  => 'margin harus berupa angka',
            'between'  => 'margin harus berupa angka antara 1 sampai dengan 100',
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return redirect()->route('tx.create-margin')->withInput()->withErrors($validator);
        } else {
            $margin = Margin::findOrFail($id);
            $margin->dari = trim($request['dari']);
            $margin->ke = trim($request['ke']);
            $margin->margin = trim($request['margin']);
            $margin->save();
            $request->session()->flash('statusmargin', 'Tersimpan!');
        }

        return redirect()->route('mst.margin.index')->with('statusmargin', 'Tersimpan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $margin = Margin::findOrFail($id);
        return $margin->delete() ? 'ok' : abort(404);
    }
}

content_mcupekerja/resources/views/margin/create.blade.php
@extends('layout_admin')
@section('title')
Data Master Margin - MCU Pekerja Admin Panel
@endsection

@section('content')
<!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Tambah Margin
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{route('home-admin')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#"><i class="fa fa-money active"></i> Tambah Margin</a></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-md-12">
              <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title">Form Tambah Margin</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="col-md-12">
                    {!! Form::open(['route' => ['mst.margin.store'], 
                        'class' => 'form-horizontal']) !!}
                      {!! csrf_field() !!}
                      <div class="form-group">
                        <label for="dari" class="col-sm-2 control-label">Dari*</label>
                        <div class="col-sm-10">
                          <input value="{{old('dari')}}" type="number" class="form-control" id="dari" name="dari" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('dari')}}</p>
                        </div>                      
                      </div>
                      <div class="form-group">
                        <label for="ke" class="col-sm-2 control-label">Ke*</label>
                        <div class="col-sm-10">
                          <input value="{{old('ke')}}" type="number" class="form-control" id="ke" name="ke" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('ke')}}</p>
                        </div>                      
                      </div>
                      <div class="form-group">
                        <label for="margin" class="col-sm-2 control-label">Prosentase Margin*</label>
                        <div class="col-sm-10">
                          <input value="{{old('margin')}}" type="number" class="form-control" id="margin" name="margin" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('margin')}}</p>
                        </div>                      
                      </div>
                      <button type="submit" class="btn btn-info pull-right">Simpan</button>
                    {!! Form::close() !!}
                  </div>
                </div><!-- /.box-body -->
              </div>
            </div>
          </div>
          <!-- Main row -->
        </section><!-- /.content -->
@endsection
@section('css')
<style>
  input[type="number"] {
    -moz-appearance: textfield;
}
input[type="number"]:hover,
input[type="number"]:focus {
    -moz-appearance: number-input;
}
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none;
  margin: 0; /* Removes leftover margin */
}
</style>
<link href="{{asset('assets/admin/plugins/select2/select2.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/iCheck/all.css')}}" rel="stylesheet">
@endsection
@section('js')
  <script src="{{asset('assets/admin/plugins/select2/select2.min.js')}}"></script>
  <script src="{{asset('assets/admin/plugins/iCheck/icheck.min.js')}}"></script>
<script type="text/javascript">
  
</script>
@endsection

content_mcupekerja/resources/views/margin/edit.blade.php
@extends('layout_admin')
@section('title')
Data Master Margin - MCU Pekerja Admin Panel
@endsection

@section('content')
<!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Tambah Margin
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{route('home-admin')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#"><i class="fa fa-money active"></i> Tambah Margin</a></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-md-12">
              <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title">Form Tambah Margin</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="col-md-12">
                    {!! Form::open(['route' => ['mst.margin.update', $margin->id], 
                        'class' => 'form-horizontal']) !!}
                        <input type="hidden" name="_method" value="PATCH">
                      {!! csrf_field() !!}
                      <div class="form-group">
                        <label for="dari" class="col-sm-2 control-label">Dari*</label>
                        <div class="col-sm-10">
                          <input value="{{old('dari', $margin->dari)}}" type="number" class="form-control" id="dari" name="dari" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('dari')}}</p>
                        </div>                      
                      </div>
                      <div class="form-group">
                        <label for="ke" class="col-sm-2 control-label">Ke*</label>
                        <div class="col-sm-10">
                          <input value="{{old('ke', $margin->ke)}}" type="number" class="form-control" id="ke" name="ke" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('ke')}}</p>
                        </div>                      
                      </div>
                      <div class="form-group">
                        <label for="margin" class="col-sm-2 control-label">Prosentase Margin*</label>
                        <div class="col-sm-10">
                          <input value="{{old('margin', $margin->margin)}}" type="number" class="form-control" id="margin" name="margin" placeholder="" required>
                          <p class="help-block" style="color:red">{{$errors->first('margin')}}</p>
                        </div>                      
                      </div>
                      <button type="submit" class="btn btn-info pull-right">Simpan</button>
                    {!! Form::close() !!}
                  </div>
                </div><!-- /.box-body -->
              </div>
            </div>
          </div>
          <!-- Main row -->
        </section><!-- /.content -->
@endsection
@section('css')
<style>
  input[type="number"] {
    -moz-appearance: textfield;
}
input[type="number"]:hover,
input[type="number"]:focus {
    -moz-appearance: number-input;
}
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none;
  margin: 0; /* Removes leftover margin */
}
</style>
<link href="{{asset('assets/admin/plugins/select2/select2.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/iCheck/all.css')}}" rel="stylesheet">
@endsection
@section('js')
  <script src="{{asset('assets/admin/plugins/select2/select2.min.js')}}"></script>
  <script src="{{asset('assets/admin/plugins/iCheck/icheck.min.js')}}"></script>
<script type="text/javascript">
  
</script>
@endsection

content_mcupekerja/resources/views/margin/list.blade.php
@extends('layout_admin')
@section('title')
Kelola Margin - MCU Pekerja Admin Panel
@endsection
@section('content')
<!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Daftar Margin
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{route('home-admin')}}"><i class="fa fa-home"></i> Home</a></li>
      <li class="active">Kelola Margin</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-2">
        <a href="{{route('mst.margin.create')}}" id="btnTambah" class="btn bg-navy margin">Tambah Margin</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
              <i class="ion ion-clipboard"></i>
              <h3 class="box-title">Daftar Margin</h3>
            </div>
          <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" id="tabel">
                            <thead>
                                <tr>
                                    <th>Dari</th>
                                    <th>Ke</th>
                                    <th>Prosentase Margin</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
@section('css')
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/admin/plugins/dataTables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/buttons.server-side.js')}}"></script>
<script>
  $(document).ready(function () {
    @if (\Session::has('statusmargin'))
      swal("Sukses!", "Prosentase Margin Tersimpan!", "success");
    @endif
    $('#tabel').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{{ route('src.margin') }}",
        "columns": [
            {data: 'dari'},
            {data: 'ke'},
            {data: 'margin'},
            {data: 'action', orderable: false, searchable: false}
        ],
        "order": [[0, 'asc']]
    });
  })
  function ubah(id){
    window.location.href = '{{ url('/mst/margin') }}' + '/' + id + '/edit'
  }
  function hapus(id){
    if(confirm('Apakah Anda yakin akan hapus data Margin ini?')){
      var token = "{{csrf_token()}}";
      $.ajax({
        url: '{{ url('/mst/margin') }}' + '/' + id,
        type: "POST",
        data: {id: id, _token: token,_method:'delete'},
        success: function(result){
          swal("Sukses!", "Margin berhasil dihapus.", "success");
          var table = $('#tabel').dataTable();
          table.fnStandingRedraw();
        }
      });
    }
  }
</script>
@endsection