content_mcupekerja/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('home', ['uses' => 'FrontController@Index', 'as' => 'home']);
Route::get('thanks', ['uses' => 'RegController@thanks', 'as' => 'thanks']);
Route::get('mitra-kami', ['uses' => 'FrontController@MitraKami', 'as' => 'mitra-kami']);
Route::get('tentang-kami', ['uses' => 'FrontController@TentangKami', 'as' => 'tentang-kami']);
Route::get('register', ['uses' => 'RegController@index', 'as' => 'register']);
// Route::get('cek-voucher/{kode}', ['uses' => 'FrontController@CekVoucher', 'as' => 'cek-voucher']);
Route::get('pdf', ['uses' => 'RegController@makepdf', 'as' => 'pdf']);
Route::get('gpdf', ['uses' => 'RegController@genpdf', 'as' => 'gpdf']);
Route::post('save-register', ['uses' => 'RegController@store', 'as' => 'save-register']);

Route::get('home-admin', array('middleware' => 'auth', 'uses' => 'FrontController@AdminHome', 'as' => 'home-admin'));
// Route::get('kelola-kode', array('middleware' => 'auth', 'uses' => 'FrontController@KelolaKode', 'as' => 'kelola-kode'));
Route::get('kelola-user', array('middleware' => 'auth', 'uses' => 'FrontController@KelolaUser', 'as' => 'kelola-user'));
Route::get('form-user', array('middleware' => 'auth', 'uses' => 'FrontController@FormUser', 'as' => 'form-user'));
Route::post('save-user', array('middleware' => 'auth', 'uses' => 'FrontController@SaveUser', 'as' => 'save-user'));
// Route::post('save-kode', array('middleware' => 'auth', 'uses' => 'FrontController@SaveKode', 'as' => 'save-kode'));
Route::get('laporan-registrasi', array('middleware' => 'auth', 'uses' => 'FrontController@LaporanRegistrasi', 'as' => 'laporan-registrasi'));
Route::get('data-listuser', array('middleware' => 'auth', 'uses' => 'FrontController@ListUser', 'as' => 'data-listuser'));
Route::get('data-listkode', array('middleware' => 'auth', 'uses' => 'FrontController@ListKode', 'as' => 'data-listkode'));
Route::post('delete-user', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteUser', 'as' => 'delete-user'));
// Route::post('delete-kode', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteKode', 'as' => 'delete-kode'));

Route::post('delete-registrasi', array('middleware' => 'auth', 'uses' => 'FrontController@DeleteRegistrasi', 'as' => 'delete-registrasi'));
Route::get('data-listregistrasi', array('middleware' => 'auth', 'uses' => 'FrontController@ListRegistrasi', 'as' => 'data-listregistrasi'));
Route::get('detil-registrasi/{id}', array('middleware' => 'auth', 'uses' => 'FrontController@DetilRegistrasi', 'as' => 'detil-registrasi'));
Route::get('export-excel/{word?}', array('middleware' => 'auth', 'uses' => 'FrontController@ExportExcel', 'as' => 'export-excel'));

Route::get('auth/login', array('uses' => 'Auth\AuthController@getLogin', 'as' => 'login'));
Route::post('auth/login', array('uses' => 'Auth\AuthController@postLogin', 'as' => 'postLogin'));
// Route::get('auth/register', array('uses' => 'Auth\AuthController@getRegister', 'as' => 'register'));
// Route::post('auth/register', array('uses' => 'Auth\AuthController@postRegister', 'as' => 'postRegister'));
Route::get('auth/logout', array('uses' => 'Auth\AuthController@getLogout', 'as' => 'logout'));

Route::get('/', function () {
    return redirect()->route('home');
});

Route::group(['middleware' => 'auth', 'prefix' => 'mst'], function () {

	Route::resource('kota', 'KotaController',
      ['except' => ['show']]);
	Route::resource('parameter', 'ParameterController',
      ['except' => ['show']]);
	Route::resource('margin', 'MarginController',
      ['except' => ['show']]);
	Route::resource('paket', 'PaketController',
      ['except' => ['show']]);
	Route::resource('notif', 'NotifController',
      ['except' => ['show']]);
	Route::get('parameter/price/{id}', 
		['uses' => 'ParameterController@price', 
		'as' => 'mst.parameter.price']);
	Route::post('parameter/price/', 
		['uses' => 'ParameterController@saveprice', 
		'as' => 'mst.parameter.save']);
	Route::get('paket/price/{id}', 
		['uses' => 'PaketController@price', 
		'as' => 'mst.paket.price']);
	Route::post('paket/price/', 
		['uses' => 'PaketController@saveprice', 
		'as' => 'mst.paket.save']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'src'], function () {
	Route::get('kota', ['uses' => 'SrcController@Kota', 'as' => 'src.kota']);
	Route::get('parameter', ['uses' => 'SrcController@Parameter', 'as' => 'src.parameter']);
	Route::get('paket', ['uses' => 'SrcController@Paket', 'as' => 'src.paket']);
	Route::get('margin', ['uses' => 'SrcController@Margin', 'as' => 'src.margin']);
	Route::get('notif', ['uses' => 'SrcController@Notif', 'as' => 'src.notif']);
	Route::get('paket-param/{id}', ['uses' => 'SrcController@PaketParam', 'as' => 'src.paket-param']);
});

Route::group(['middleware' => 'auth', 'prefix' => 'tx'], function () {
	Route::get('param/{id}', ['uses' => 'TxController@param', 'as' => 'tx.param']);
	Route::get('create/{id}', ['uses' => 'TxController@create', 'as' => 'tx.create']);
	Route::post('save/{id}', ['uses' => 'TxController@save', 'as' => 'tx.save']);
	Route::delete('param/{id}', ['uses' => 'TxController@del', 'as' => 'tx.del']);
	
});

content_mcupekerja/resources/views/form_user.blade.php
@extends('layout_admin')
@section('title')
Tambah User - MCU Pekerja Admin Panel
@endsection

@section('content')
<!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Tambah User
            <small>MCU Pekerja</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{route('home-admin')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('kelola-user')}}"><i class="fa fa-people active"></i> Kelola User</a></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-md-12">
              <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title">Form User</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="col-md-12">
                    <form class="form-horizontal" action="{{route('save-user')}}" method="post">
                      {!! csrf_field() !!}
                      <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Nama*</label>
                        <div class="col-sm-10">
                          <input value="{{old('name')}}" type="text" class="form-control" id="name" name="name" placeholder="Masukkan Nama" required>
                          <p class="help-block" style="color:red">{{$errors->first('name')}}</p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Username*</label>
                        <div class="col-sm-10">
                          <input value="{{old('username')}}" type="text" class="form-control" id="username" name="username" placeholder="Masukkan Username" required>
                          <p class="help-block" style="color:red">{{$errors->first('username')}}</p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Password*</label>
                        <div class="col-sm-10">
                          <input type="password" class="form-control" id="password" name="password" placeholder="Masukkan Password" required>
                          <p class="help-block" style="color:red">{{$errors->first('password')}}</p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Ulangi Password*</label>
                        <div class="col-sm-10">
                          <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Ulangi Password" required>
                          <p class="help-block" style="color:red">{{$errors->first('password_confirmation')}}</p>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-info pull-right">Simpan</button>
                    </form>
                  </div>
                </div><!-- /.box-body -->
              </div>
            </div>
          </div>
          <!-- Main row -->
        </section><!-- /.content -->
@endsection
@section('css')
<style>
  input[type="number"] {
    -moz-appearance: textfield;
}
input[type="number"]:hover,
input[type="number"]:focus {
    -moz-appearance: number-input;
}
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none;
  margin: 0; /* Removes leftover margin */
}
</style>
@endsection
@section('js')
<script>
    $(document).ready(function () {
      $(".select2").select2();
      var sukses = "{{session('registered')}}";
      if(sukses == "1"){
        swal("Sukses!", "User berhasil dibuat.", "success");
      }
    });
</script>
@endsection

content_mcupekerja/resources/views/home.blade.php
@extends('layout')
@section('title')
MCU Pekerja
@endsection
@section('content')
<!--=== Slider ===-->
		<div class="slider-inner">
			<div id="da-slider" class="da-slider">
				<div class="da-slide">
					<h2><i>SELAMAT DATANG</i> <br/> <i>DI PLATFORM ONLINE MEDICAL CHECK UP PEKERJA</i> <br/> <i>YANG PERTAMA DI INDONESIA</i> </h2>
					<!-- <div class="da-img"><img class="img-responsive" src="assets/plugins/parallax-slider/img/1.png" alt=""></div> -->
				</div>
				<!-- <div class="da-slide">
					<h2><i>Visi :</i> <br /> <i>Menjadi laboratorium klinik yang terpilih karena kualitas</i> <br/> <i>pemeriksaan dan pelayanan terbaik bagi kesehatan tenaga kerja</i></h2>	
				</div>
				<div class="da-slide">
					<h2><i>USING BEST WEB</i> <br /> <i>SOLUTIONS WITH</i> <br /> <i>HTML5/CSS3</i></h2>
					<p><i>Lorem ipsum dolor amet</i> <br /> <i>tempor incididunt ut</i> <br /> <i>veniam omnis </i></p>
					<div class="da-img"><img src="assets/plugins/parallax-slider/img/html5andcss3.png" alt="image01" /></div>
				</div> -->
				<div class="da-arrows">
					<span class="da-arrows-prev"></span>
					<span class="da-arrows-next"></span>
				</div>
			</div>
		</div><!--/slider-->
		<!--=== End Slider ===-->
<div class="purchase">
	<div class="container overflow-h">
		<div class="row">
			<div class="col-md-9 animated fadeInLeft">
				{{-- <span>Selamat Datang di Platform Online Medical Check Up Pekerja Yang Pertama di Indonesia!</span> --}}
			</div>
			<div class="col-md-3 btn-buy animated fadeInRight">
				{{-- <a href="{{route('register')}}" class="btn-u btn-u-lg"><i class="fa fa-check"></i> Daftar</a> --}}
			</div>
		</div>
	</div>
</div>
@endsection

content_mcupekerja/resources/views/home_admin.blade.php
@extends('layout_admin')
@section('title')
MCU Pekerja - Admin
@endsection
@section('content')
<!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            MCU Pekerja
            <small>Admin Panel</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard active"></i> Home</a></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="alert alert-success alert-dismissable">
            <h4><i class="icon fa fa-check"></i> Selamat Datang!</h4>
            Di Web Admin Panel MCUPekerja.com
          </div>

          <div class="row">
            <div class="col-lg-4 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>{{ $thn }}</h3>
                  <p>Registrasi Total</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{{ route('laporan-registrasi') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>

            <div class="col-lg-4 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>{{ $bln }}</h3>
                  <p>Registrasi Bulan Ini</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{{ route('laporan-registrasi') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <div class="col-lg-4 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h3>{{ $minggu }}</h3>
                  <p>Registrasi Mingu ini</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{{ route('laporan-registrasi') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
          </div>
          
        </section><!-- /.content -->


@endsection
@section('css')
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/admin/plugins/knob/jquery.knob.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/buttons.server-side.js')}}"></script>
<script>
    $(document).ready(function () {
      // $('#tabel').DataTable({
      //       "processing": true,
      //       "serverSide": true,
      //       // "bFilter": false,
      //       "ajax": "{{-- route('jsontabledashboard') --}}",
      //       "columns": [
      //           {data: 'tgl_mulai_proyek', name: 'tgl_mulai_proyek', width: '5%'},
      //           {data: 'pekerjaan', name: 'pekerjaan', width: '15%'},
      //           {data: 'rencana_total', name: 'rencana_total', width: '10%'},
      //           {data: 'realisasi_total', name: 'realisasi_total', width: '10%'},
      //       ],
      //       "order": [[0, 'desc']]
      // });
    });
    $(function() {
        $(".dial").knob();
    });
</script>
@endsection

content_mcupekerja/resources/views/kelola_user.blade.php
@extends('layout_admin')
@section('title')
Kelola User - MCU Pekerja Admin Panel
@endsection
@section('content')
<!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      User
      <small>Kelola User</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{route('home-admin')}}"><i class="fa fa-home"></i> Home</a></li>
      <li class="active">Kelola User</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-2">
        <a href="{{route('form-user')}}" id="btnTambah" class="btn bg-navy margin">Tambah User</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
              <i class="ion ion-clipboard"></i>
              <h3 class="box-title">Daftar User</h3>
            </div>
          <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" id="tabel">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Username</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
@section('css')
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/admin/plugins/dataTables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.bootstrap.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.responsive.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/dataTables.tableTools.min.js')}}"></script>
<script src="{{asset('assets/admin/plugins/dataTables/buttons.server-side.js')}}"></script>
<script>
  $(document).ready(function () {
    var sukses = "{{session('registered')}}";
      if(sukses == "1"){
        swal("Sukses!", "User berhasil dibuat.", "success");
      }
    $('#tabel').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{{ route('data-listuser') }}",
        "columns": [
            {data: 'name'},
            {data: 'username'},
            {data: 'action', orderable: false, searchable: false}
        ],
        "order": [[0, 'asc']]
    });
  })
  function hapus(id){
    if(confirm('Apakah Anda yakin akan hapus user ini?')){
      var token = "{{csrf_token()}}";
      $.ajax({
        url: "{{route('delete-user')}}",
        type: "POST",
        data: {id_user: id, _token: token},
        success: function(result){
          swal("Sukses!", "User berhasil dihapus.", "success");
          var table = $('#tabel').dataTable();
          table.fnStandingRedraw();
        }
      });
    }
  }
</script>
@endsection

content_mcupekerja/resources/views/layout_admin.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" href="{{asset('assets/img/logo.jpg')}}" type="image/gif">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{{asset('assets/admin/bootstrap/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('assets/admin/plugins/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('assets/admin/css/ionicons/css/ionicons.min.css')}}">
    <!-- Theme style -->
    @yield('css')
    <link rel="stylesheet" href="{{asset('assets/admin/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('assets/admin/css/skins/_all-skins.min.css')}}">
    <link href="{{asset('assets/admin/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet">
    
  </head>
  <body class="hold-transition skin-red-light sidebar-mini">
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>MCU</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>MCU</b>Pekerja</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{asset('assets/admin/img/users.png')}}" class="user-image" alt="User Image">
                  <span class="hidden-xs">{{Auth::user()->name}}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{asset('assets/admin/img/users.png')}}" class="img-circle" alt="User Image">
                    <p>
                      {{Auth::user()->name}}
                      <small>{{Auth::user()->username}}</small>
                    </p>
                  </li>
                  <li class="user-footer">
                    <!-- <div class="pull-left">
                      <a href="#" class="btn btn-primary btn-flat">Ubah Password</a>
                    </div> -->
                    <div class="pull-right">
                      <a href="{{\URL::to('auth/logout')}}" class="btn btn-danger btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{{asset('assets/admin/img/users.png')}}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>{{Auth::user()->name}}</p>
              <a href="#"><i class="fa fa-circle text-success"></i> {{Auth::user()->username}}</a>
            </div>
          </div>
          
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MENU UTAMA</li>
            <li><a href="{{route('home-admin')}}"><i class="fa fa-home"></i> <span>Home</span></a></li>
            <li><a href="{{route('laporan-registrasi')}}"><i class="fa fa-archive"></i> <span>Laporan Registrasi</span></a></li>
            <li class="header">MASTER DATA</li>
            <li><a href="{{route('mst.kota.index')}}"><i class="fa fa-building"></i> <span>Master Kota</span></a></li>
            <li><a href="{{route('mst.parameter.index')}}"><i class="fa fa-gear"></i> <span>Master Parameter</span></a></li>
            <li><a href="{{route('mst.paket.index')}}"><i class="fa fa-archive"></i> <span>Master Paket</span></a></li>
            <li class="header">SUPPORT</li>
            <!-- <li><a href="{{--route('kelola-kode')--}}"><i class="fa fa-list"></i> <span>Kode Voucher</span></a></li> -->
            <li><a href="{{route('kelola-user')}}"><i class="fa fa-users"></i> <span>User</span></a></li>
            <li><a href="{{route('mst.notif.index')}}"><i class="fa fa-envelope"></i> <span>Email Notifikasi</span></a></li>
            <li><a href="{{route('mst.margin.index')}}"><i class="fa fa-money"></i> <span>Margin</span></a></li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        @yield('content')
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0.0
        </div>
        <strong>Copyright &copy; 2017 <a target="_blank" href="#">Emcorp Studio</a>.</strong> All rights reserved.
      </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="{{asset('assets/admin/plugins/jQuery/jQuery-2.1.4.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/jquery-ui.min.js')}}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{{asset('assets/admin/bootstrap/js/bootstrap.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('assets/admin/js/app.min.js')}}"></script>
    <script src="{{asset('assets/admin/plugins/sweetalert/sweetalert.min.js')}}"></script>
    @yield('js')
    <script type="text/javascript">
      function isValidDate(date_string)
      {
        var pattern = /^([0-9]{2})\-([0-9]{2})\-([0-9]{4})$/;
        return pattern.test(date_string);
      }
    </script>
  </body>
</html>

content_mcupekerja/resources/views/tentang_kami.blade.php
@extends('layout')
@section('title')
Tentang Kami - MCU Pekerja
@endsection
@section('content')
<div class="container content">
	<div class="headline"><h2>Tentang Kami</h2></div>
	<div class="row margin-bottom-40">
		<div class="col-md-6 md-margin-bottom-40">
			<p>MCUPekerja memiliki visi yaitu Menjadi laboratorium klinik yang terpilih karena kualitas pemeriksaan dan pelayanan terbaik bagi kesehatan tenaga kerja.</p>
			<h4>Misi</h4>
			<ul class="list-unstyled">
				<li><i class="fa fa-check color-green"></i> Menyelenggarakan pelayanan Medical Check Up terpadu bagi kesehatan tenaga kerja.</li>
				<li><i class="fa fa-check color-green"></i> Memiliki sumber daya manusia yang trampil, cepat, teliti , ramah dan profesional serta mampu mengikuti perkembangan ilmu dan teknologi.</li>
				<li><i class="fa fa-check color-green"></i> Menjalin dan memelihara kerjasama yang baik dengan pelanggan dan mitra kerja.</li>
				<li><i class="fa fa-check color-green"></i> Menerapkan prinsip kerja cepat dan akurat yang berfokus pada keselamatan pasien.</li>
			</ul><br />

			<h4>Motto</h4>
			<p>SEHAT AKAN MENINGKATKAN PRODUKTIFITAS</p>
		</div>

		<div class="col-md-6 text-center md-margin-bottom-40">
			<div class="responsive-video">
				<img src="{{asset('assets/img/logo_white.jpg')}}">
			</div>
		</div>
	</div><!--/row-->
</div>
@endsection

content_mcupekerja/resources/views/thanks.blade.php
@extends('layout')
@section('title')
Terima Kasih
@endsection
@section('content')

<div class="container content">
	<div class="headline"><h2>Terima Kasih Data Anda berhasil didaftarkan</h2></div>
	<div class="row">
		<div class="col-md-3 btn-buy animated fadeInleft">
			<a href="{{url($reg->file)}}" target="_blank" class="btn-u btn-u-lg"><i class="fa fa-arrow-down"></i> Download Quotation</a>
		</div>
		<div class="col-md-6 animated fadeInLeft">
		</div>
		<div class="col-md-3 btn-buy animated fadeInRight">
			<a href="{{route('home')}}" class="btn-u btn-u-lg"><i class="fa fa-arrow-left"></i> Kembali ke Beranda</a>
		</div>
	</div>
</div>
				
@endsection
@section('css')
	
@endsection
@section('js')

@endsection